name: Push /www to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./www
